// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// <define:import.meta.env>
var define_import_meta_env_default = { VITE_SUPABASE_PROJECT_ID: "mktcyipfxgwrbeinakdb", VITE_SUPABASE_PUBLISHABLE_KEY: "sb_publishable_E0B5v8wvc6fvRrRnzmSeAQ_Q2KbPvub", VITE_SUPABASE_URL: "https://c--62fbdcc7-5ed1-474b-8ab7-05f560e3247d-prod.lovable.cloud", VITE_SUPABASE_ANON_KEY: "sb_publishable_E0B5v8wvc6fvRrRnzmSeAQ_Q2KbPvub", MODE: "production", BASE_URL: "/", DEV: false, PROD: true, SSR: false };

// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/get-dashboard-summary.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/data/applications.ts
function toNumber(value, field, app) {
  if (typeof value === "number" && Number.isFinite(value)) return value;
  throw new Error(`\u0412 API \u043D\u0435\u0442 \u0447\u0438\u0441\u043B\u043E\u0432\u043E\u0433\u043E \u043F\u043E\u043B\u044F \xAB${field}\xBB \u0434\u043B\u044F \u0433\u0440\u0443\u043F\u043F\u044B \xAB${app.group}\xBB (${app.id}).`);
}
function toNullableNumber(value) {
  return typeof value === "number" && Number.isFinite(value) ? value : null;
}
function toBasis(value) {
  if (value === "\u0411\u044E\u0434\u0436\u0435\u0442" || value === "\u041F\u043B\u0430\u0442\u043D\u043E\u0435") return value;
  throw new Error(`\u041D\u0435\u0438\u0437\u0432\u0435\u0441\u0442\u043D\u0430\u044F \u043E\u0441\u043D\u043E\u0432\u0430 \u043F\u043E\u0441\u0442\u0443\u043F\u043B\u0435\u043D\u0438\u044F \u0432 API: \xAB${value}\xBB.`);
}
function mapApplication(app) {
  const basis = toBasis(app.basis);
  const confirmation = basis === "\u0411\u044E\u0434\u0436\u0435\u0442" ? `\u0421\u043E\u0433\u043B\u0430\u0441\u0438\u0435: ${app.consent || "\u2014"}` : `\u0414\u043E\u0433\u043E\u0432\u043E\u0440: ${app.contract || "\u2014"}`;
  return {
    id: String(app.id),
    university: app.university,
    basis,
    group: app.group,
    priority: toNumber(app.priority, "\u041F\u0440\u0438\u043E\u0440\u0438\u0442\u0435\u0442", app),
    score: toNumber(app.score, "\u0411\u0430\u043B\u043B \u0415\u043B\u0438\u0441\u0435\u044F", app),
    scoreBreakdown: "",
    position: toNumber(app.generalPosition, "\u041F\u043E\u0437\u0438\u0446\u0438\u044F \u043E\u0431\u0449\u0430\u044F", app),
    status: app.status || "\u041D\u0435\u0442 \u0434\u0430\u043D\u043D\u044B\u0445",
    consent: confirmation,
    snapshot: app.snapshot || "\u041D\u0435\u0442 \u0434\u0430\u0442\u044B \u0441\u043F\u0438\u0441\u043A\u0430",
    control: {
      seats: toNullableNumber(app.seats),
      semesterFeeText: app.semesterFeeText ?? null,
      contractsCount: toNullableNumber(app.contractsCount),
      contractsAbove: toNullableNumber(app.contractsAbove),
      consentsCount: toNullableNumber(app.consentsCount),
      consentsAbove: toNullableNumber(app.consentsAbove),
      contractRank: toNullableNumber(app.contractRank),
      consentRank: toNullableNumber(app.consentRank),
      sourceNote: app.activeSource || "\u041F\u0440\u0435\u0434\u0432\u0430\u0440\u0438\u0442\u0435\u043B\u044C\u043D\u043E \u043F\u043E \u043E\u0431\u0449\u0435\u0439 \u043F\u043E\u0437\u0438\u0446\u0438\u0438"
    },
    generalChange: app.generalChange || "\u041D\u0435\u0442 \u043F\u0440\u0435\u0434\u044B\u0434\u0443\u0449\u0435\u0433\u043E \u0441\u043F\u0438\u0441\u043A\u0430",
    activeChange: app.activeChange || "\u041D\u0435\u0442 \u0441\u043E\u043F\u043E\u0441\u0442\u0430\u0432\u0438\u043C\u043E\u0439 \u0430\u043A\u0442\u0438\u0432\u043D\u043E\u0439 \u043F\u043E\u0437\u0438\u0446\u0438\u0438"
  };
}
async function getDashboardData() {
  const endpoint = define_import_meta_env_default.VITE_GAS_ENDPOINT;
  if (!endpoint) {
    throw new Error("\u041D\u0435 \u0437\u0430\u0434\u0430\u043D \u0430\u0434\u0440\u0435\u0441 read-only API. \u0414\u043E\u0431\u0430\u0432\u044C\u0442\u0435 VITE_GAS_ENDPOINT \u0432 \u043D\u0430\u0441\u0442\u0440\u043E\u0439\u043A\u0438 \u043F\u0440\u043E\u0435\u043A\u0442\u0430.");
  }
  const response = await fetch(endpoint, {
    cache: "no-store",
    redirect: "follow"
  });
  if (!response.ok) {
    throw new Error(`API \u0432\u0435\u0440\u043D\u0443\u043B \u043E\u0448\u0438\u0431\u043A\u0443 ${response.status}.`);
  }
  const payload = await response.json();
  if (!payload?.meta || !Array.isArray(payload.applications) || !Array.isArray(payload.coverage)) {
    throw new Error("API \u0432\u0435\u0440\u043D\u0443\u043B \u043E\u0442\u0432\u0435\u0442 \u0432 \u043D\u0435\u043E\u0436\u0438\u0434\u0430\u043D\u043D\u043E\u043C \u0444\u043E\u0440\u043C\u0430\u0442\u0435.");
  }
  return {
    meta: { ...payload.meta, candidateName: "\u0415\u043B\u0438\u0441\u0435\u0439" },
    applications: payload.applications.filter((app) => app.hasList).map(mapApplication),
    coverage: payload.coverage
  };
}
function buildAnalyticalPhrase(app) {
  const above = app.position - 1;
  return app.basis === "\u0411\u044E\u0434\u0436\u0435\u0442" ? `\u0412\u044B\u0448\u0435 ${above} \u0430\u0431\u0438\u0442\u0443\u0440\u0438\u0435\u043D\u0442\u043E\u0432. \u0414\u043B\u044F \u0442\u043E\u0447\u043D\u043E\u0439 \u043E\u0446\u0435\u043D\u043A\u0438 \u043D\u0443\u0436\u043D\u044B \u043A\u0432\u043E\u0442\u0430 \u0438 \u0447\u0438\u0441\u043B\u043E \u0430\u0431\u0438\u0442\u0443\u0440\u0438\u0435\u043D\u0442\u043E\u0432 \u0432\u044B\u0448\u0435 \u0441 \u043F\u043E\u0434\u0442\u0432\u0435\u0440\u0436\u0434\u0451\u043D\u043D\u044B\u043C \u0441\u043E\u0433\u043B\u0430\u0441\u0438\u0435\u043C.` : `\u0412\u044B\u0448\u0435 ${above} \u0430\u0431\u0438\u0442\u0443\u0440\u0438\u0435\u043D\u0442\u043E\u0432. \u0414\u043B\u044F \u0442\u043E\u0447\u043D\u043E\u0439 \u043E\u0446\u0435\u043D\u043A\u0438 \u043D\u0443\u0436\u043D\u044B \u0434\u043E\u0433\u043E\u0432\u043E\u0440\u043D\u044B\u0435 \u043C\u0435\u0441\u0442\u0430 \u0438 \u043A\u043E\u043B\u0438\u0447\u0435\u0441\u0442\u0432\u043E \u0434\u043E\u0433\u043E\u0432\u043E\u0440\u043E\u0432 \u0432\u044B\u0448\u0435 \u043F\u043E \u0441\u043F\u0438\u0441\u043A\u0443.`;
}

// src/lib/mcp/tools/get-dashboard-summary.ts
var get_dashboard_summary_default = defineTool({
  name: "get_dashboard_summary",
  title: "\u0421\u0432\u043E\u0434\u043A\u0430 \u0434\u0430\u0448\u0431\u043E\u0440\u0434\u0430",
  description: "\u0412\u043E\u0437\u0432\u0440\u0430\u0449\u0430\u0435\u0442 \u043E\u0431\u0449\u0443\u044E \u0441\u0432\u043E\u0434\u043A\u0443 \u043F\u043E \u043F\u043E\u0441\u0442\u0443\u043F\u043B\u0435\u043D\u0438\u044E \u0415\u043B\u0438\u0441\u0435\u044F (\u21161431604): \u043C\u0435\u0442\u0430-\u0438\u043D\u0444\u043E\u0440\u043C\u0430\u0446\u0438\u044E, \u043F\u043E\u043A\u0440\u044B\u0442\u0438\u0435 \u0441\u043F\u0438\u0441\u043A\u0430\u043C\u0438 \u043F\u043E \u0432\u0443\u0437\u0430\u043C \u0438 \u0430\u0433\u0440\u0435\u0433\u0430\u0442\u044B (\u043F\u043E\u043B\u0443\u0447\u0435\u043D\u043E \u0441\u043F\u0438\u0441\u043A\u043E\u0432, \u0431\u044E\u0434\u0436\u0435\u0442/\u043F\u043B\u0430\u0442\u043D\u043E\u0435, \u0441\u0442\u0430\u0434\u0438\u044F \u043A\u043E\u043D\u043A\u0443\u0440\u0441\u0430).",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async () => {
    const data = await getDashboardData();
    return {
      content: [{ type: "text", text: JSON.stringify({ meta: data.meta, coverage: data.coverage }, null, 2) }],
      structuredContent: { meta: data.meta, coverage: data.coverage }
    };
  }
});

// src/lib/mcp/tools/list-applications.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z } from "npm:zod@^3.25.76";
var list_applications_default = defineTool2({
  name: "list_applications",
  title: "\u0421\u043F\u0438\u0441\u043E\u043A \u0437\u0430\u044F\u0432\u043B\u0435\u043D\u0438\u0439",
  description: "\u0412\u043E\u0437\u0432\u0440\u0430\u0449\u0430\u0435\u0442 \u0437\u0430\u043F\u0438\u0441\u0438 \u0438\u0437 \u043A\u043E\u043D\u043A\u0443\u0440\u0441\u043D\u044B\u0445 \u0441\u043F\u0438\u0441\u043A\u043E\u0432 \u0441 \u043D\u0435\u043E\u0431\u044F\u0437\u0430\u0442\u0435\u043B\u044C\u043D\u043E\u0439 \u0444\u0438\u043B\u044C\u0442\u0440\u0430\u0446\u0438\u0435\u0439 \u043F\u043E \u0432\u0443\u0437\u0443 \u0438 \u043E\u0441\u043D\u043E\u0432\u0435 (\u0411\u044E\u0434\u0436\u0435\u0442/\u041F\u043B\u0430\u0442\u043D\u043E\u0435) \u0438 \u0441\u043E\u0440\u0442\u0438\u0440\u043E\u0432\u043A\u043E\u0439 \u043F\u043E \u043F\u043E\u0437\u0438\u0446\u0438\u0438.",
  inputSchema: {
    university: z.string().optional().describe("\u0424\u0438\u043B\u044C\u0442\u0440 \u043F\u043E \u043D\u0430\u0437\u0432\u0430\u043D\u0438\u044E \u0432\u0443\u0437\u0430, \u043D\u0430\u043F\u0440. '\u0421\u041F\u0431\u0413\u0423\u041F\u0422\u0414'."),
    basis: z.enum(["\u0411\u044E\u0434\u0436\u0435\u0442", "\u041F\u043B\u0430\u0442\u043D\u043E\u0435"]).optional().describe("\u0424\u0438\u043B\u044C\u0442\u0440 \u043F\u043E \u043E\u0441\u043D\u043E\u0432\u0435 \u043F\u043E\u0441\u0442\u0443\u043F\u043B\u0435\u043D\u0438\u044F."),
    limit: z.number().int().positive().max(100).optional().describe("\u041C\u0430\u043A\u0441\u0438\u043C\u0443\u043C \u0437\u0430\u043F\u0438\u0441\u0435\u0439 \u0432 \u043E\u0442\u0432\u0435\u0442\u0435.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ university, basis, limit }) => {
    const data = await getDashboardData();
    let rows = data.applications;
    if (university) rows = rows.filter((a) => a.university === university);
    if (basis) rows = rows.filter((a) => a.basis === basis);
    rows = [...rows].sort((a, b) => a.position - b.position);
    if (limit) rows = rows.slice(0, limit);
    const enriched = rows.map((a) => ({ ...a, note: buildAnalyticalPhrase(a) }));
    return {
      content: [{ type: "text", text: JSON.stringify(enriched, null, 2) }],
      structuredContent: { count: enriched.length, applications: enriched }
    };
  }
});

// src/lib/mcp/tools/get-top-positions.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z2 } from "npm:zod@^3.25.76";
var get_top_positions_default = defineTool3({
  name: "get_top_positions",
  title: "\u041B\u0443\u0447\u0448\u0438\u0435 \u0442\u0435\u043A\u0443\u0449\u0438\u0435 \u043F\u043E\u0437\u0438\u0446\u0438\u0438",
  description: "\u0412\u043E\u0437\u0432\u0440\u0430\u0449\u0430\u0435\u0442 N \u043D\u0430\u0438\u043B\u0443\u0447\u0448\u0438\u0445 (\u0441\u0430\u043C\u044B\u0445 \u0431\u043B\u0438\u0437\u043A\u0438\u0445 \u043A \u043D\u0430\u0447\u0430\u043B\u0443) \u0442\u0435\u043A\u0443\u0449\u0438\u0445 \u043F\u043E\u0437\u0438\u0446\u0438\u0439 \u0415\u043B\u0438\u0441\u0435\u044F \u043F\u043E \u0432\u0441\u0435\u043C \u043F\u043E\u043B\u0443\u0447\u0435\u043D\u043D\u044B\u043C \u043A\u043E\u043D\u043A\u0443\u0440\u0441\u043D\u044B\u043C \u0441\u043F\u0438\u0441\u043A\u0430\u043C.",
  inputSchema: {
    count: z2.number().int().positive().max(20).optional().describe("\u0421\u043A\u043E\u043B\u044C\u043A\u043E \u043F\u043E\u0437\u0438\u0446\u0438\u0439 \u0432\u0435\u0440\u043D\u0443\u0442\u044C (\u043F\u043E \u0443\u043C\u043E\u043B\u0447\u0430\u043D\u0438\u044E 6).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ count }) => {
    const data = await getDashboardData();
    const top = [...data.applications].sort((a, b) => a.position - b.position).slice(0, count ?? 6);
    return {
      content: [{ type: "text", text: JSON.stringify(top, null, 2) }],
      structuredContent: { top }
    };
  }
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "eliseus-admissions-mcp",
  title: "\u0422\u0440\u0435\u043A\u0435\u0440 \u043F\u043E\u0441\u0442\u0443\u043F\u043B\u0435\u043D\u0438\u044F \u0415\u043B\u0438\u0441\u0435\u044F \u2014 MCP",
  version: "0.1.0",
  instructions: "\u0418\u043D\u0441\u0442\u0440\u0443\u043C\u0435\u043D\u0442\u044B \u0434\u043B\u044F \u0447\u0442\u0435\u043D\u0438\u044F \u0434\u0430\u0448\u0431\u043E\u0440\u0434\u0430 \u043F\u043E\u0441\u0442\u0443\u043F\u043B\u0435\u043D\u0438\u044F \u0430\u0431\u0438\u0442\u0443\u0440\u0438\u0435\u043D\u0442\u0430 \u0415\u043B\u0438\u0441\u0435\u044F (\u21161431604, \u043A\u0430\u043C\u043F\u0430\u043D\u0438\u044F 2026). \u0418\u0441\u043F\u043E\u043B\u044C\u0437\u0443\u0439\u0442\u0435 get_dashboard_summary \u0434\u043B\u044F \u043E\u0431\u0449\u0435\u0439 \u043A\u0430\u0440\u0442\u0438\u043D\u044B, list_applications \u0434\u043B\u044F \u0434\u0435\u0442\u0430\u043B\u044C\u043D\u044B\u0445 \u0437\u0430\u043F\u0438\u0441\u0435\u0439 \u0441 \u0444\u0438\u043B\u044C\u0442\u0440\u0430\u043C\u0438 \u043F\u043E \u0432\u0443\u0437\u0443/\u043E\u0441\u043D\u043E\u0432\u0435, get_top_positions \u0434\u043B\u044F \u0431\u043B\u0438\u0436\u0430\u0439\u0448\u0438\u0445 \u043A \u043D\u0430\u0447\u0430\u043B\u0443 \u0441\u043F\u0438\u0441\u043A\u0430 \u043F\u043E\u0437\u0438\u0446\u0438\u0439. \u0414\u0430\u043D\u043D\u044B\u0435 \u2014 \u0441\u043D\u0438\u043C\u043E\u043A \u043A\u043E\u043D\u043A\u0443\u0440\u0441\u043D\u044B\u0445 \u0441\u043F\u0438\u0441\u043A\u043E\u0432; \u043E\u0431\u0449\u0430\u044F \u043F\u043E\u0437\u0438\u0446\u0438\u044F \u2260 \u043F\u0440\u043E\u0433\u043D\u043E\u0437 \u043F\u043E\u0441\u0442\u0443\u043F\u043B\u0435\u043D\u0438\u044F.",
  tools: [get_dashboard_summary_default, list_applications_default, get_top_positions_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
